jobs:
- name: deploy
  plan:
  - get: release
    trigger: true
  - put: production
    params:
      chart: release/concourse-auth-gateway-0.0.1.tgz
      wait_until_ready: 120
      replace: true
      override_values:
      - key: concourseUrl
        value: ((concourseUrl))
      - key: credentialEncryption.secret
        value: ((secret))
        hide: true
      - key: credentialEncryption.salt
        value: ((salt))
        hide: true
      - key: credentialEncryption.iterations
        value: ((iterations))
        hide: true
      - key: imageName
        value: ((imageName))
      - key: redisDockerImage
        value: ((redisDockerImage))
      - key: ingress.hostname
        value: ((ingressHostname))
      - key: ingress.enabled
        value: ((ingressEnabled))
      - key: service.type
        value: ((serviceType))

resources:
- name: release
  type: github-release
  source:
    owner: timotto
    repository: concourse-auth-gateway
    access_token: ((github-release-token))
- name: production
  type: helm
  source:
    admin_cert: ((helm-rpi.admin_cert))
    admin_key: ((helm-rpi.admin_key))
    cluster_ca: ((helm-rpi.cluster_ca))
    cluster_url: ((helm-rpi.cluster_url))
    namespace: ((cluster.namespace))
    release: ((cluster.release))

resource_types:
- name: helm
  type: registry-image
  source:
    repository: linkyard/concourse-helm-resource
