apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: concourse-auth-gateway
spec:
  selector:
    matchLabels:
      app: concourse-auth-gateway
  replicas: {{.Values.replicas}}
  template:
    metadata:
      labels:
        app: concourse-auth-gateway
    spec:
      containers:
        - name: concourse-auth-gateway
          image: {{.Values.imageName}}:{{.Values.imageTag}}
          imagePullPolicy: {{.Values.imagePullPolicy}}
          env:
{{- if .Values.concourseUrl }}
          - name: CONCOURSE_URL
            value: {{ .Values.concourseUrl }}
{{- end }}
{{- if (.Values.redis.enabled) or .Values.redis.external}}
          - name: REDIS_URL
{{- if .Values.redis.external}}
            value: {{.Values.redis.externalRedisUrl}}
{{- else }}
            value: redis://redis-service:6379
{{- end}}
          - name: SECRET
            value: {{.Values.credentialEncryption.secret}}
          - name: SALT
            value: {{.Values.credentialEncryption.salt}}
          - name: DIGEST
            value: {{.Values.credentialEncryption.digest}}
          - name: ITERATIONS
            value: {{.Values.credentialEncryption.iterations | quote}}
          {{- range $key, $value := .Values.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
{{- end}}
          resources:
            limits:
              cpu: "0.5"
              memory: "60Mi"
            requests:
              cpu: "0.2"
              memory: "30Mi"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 5
          ports:
          - containerPort: 3001
