replicas: 2
imageName: timotto/concourse-auth-gateway
imagepullPolicy: Always
redisDockerImage: redis
credentialEncryption:
  secret: changeme
  salt: changeme
  digest: sha512
  iterations: 100000
ingress:
  hostname: concourse-auth-gateway
  enabled: false
service:
  type: ClusterIP
  port: 80
env:
